### ISSUE TITLE
<span> instead of <div>?

### ISSUE THREAD

**Issue by jenseng** [amireh/canvas_react_i18n#8]
although if your `<Text>` contains block elements, you probably do want a `<div>`

one though would be we could make it configurable/overridable? e.g. `<Text tag="span">...`

**Comment by amireh** [comment]
Yeah, I'd keep using `<div>` and make it configurable, though I'd think the prop should be named `tagName`. Maybe we could add a class to the generated div? Then one can style it to have a `display: inline-block;` if they want to achieve a span-like style, but keep the markup valid.

**Comment by jenseng** [comment]
i wonder though if span would be a better default? with div you could also end up with invalid markup, e.g. if your `<Text>` is inside an inline element.

for example, looking at bridge's usage of the `{{#t}}` handlebars helper, there are almost 100 times we call it inside an inline element, and there are zero times where it wraps block elements (20 occurrences of it wrapping inline elements though)

+1 `tagName` and `className` anyway

**Comment by jenseng** [comment]
one more thought, we could the default overridable at the transform level, i.e. have an option you could pass in. then apps that want divs could easily have them by default, apps that want spans could do the same... no need to put `tagName` everywhere

**Comment by amireh** [comment]
I like having the default configurable, let's go for that, and with the tagName option, one will have full control over it.
